apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-224614-rg35-service
spec:
  selector:
    app: enterprise-system-224614-rg35
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
